files:
  - source: /*.html
    translation: '%original_path%/%original_file_name%'
  - source: file samples/Sample.csv
    translation: /file samples/%locale%.%original_file_name%
    scheme: 'identifier,source_or_translation'
  - source: file samples/Multilingual_spreadsheet_sample.csv
    translation: /multi/%two_letters_code%.%original_file_name%
    multilingual_spreadsheet: '1'
    first_line_contains_header: '1'
    scheme: 'identifier,context,source_phrase,es-ES,fr,max_length'
  - source: /**/*.md
    translation: /%original_path%/%locale%/%original_file_name%
